id: I98BD7F4C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T21:15:16+00:00'
last_modified: '2022-06-07T17:11:17.439369+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4280
  title: དཀོན་མཆོག་རྗེས་དྲན་གྱི་འགྲེལ་པ་དང་ངེས་སྒྲོན་གྱི་རྩ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D307:
      image_group_id: I3CN4306
      title: ''
      total_pages: 130
      order: 1
      base_file: D307.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
