id: P003045
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4280
  title: དཀོན་མཆོག་རྗེས་དྲན་གྱི་འགྲེལ་པ་དང་ངེས་སྒྲོན་གྱི་རྩ་བ།
  author: ''
  volumes:
    f222937819d646a583191e6b1f9c27df:
      image_group_id: I3CN4306
      title: ''
      volume_number: 1
      total_pages: 130
